package bitcamp.java110.cms.dao.impl;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import bitcamp.java110.cms.annotation.Component;
import bitcamp.java110.cms.dao.DaoException;
import bitcamp.java110.cms.dao.StudentDao;
import bitcamp.java110.cms.domain.Manager;
import bitcamp.java110.cms.domain.Student;



@Component
public class StudentJdbcDao implements StudentDao{

    public int insert(Student student) {
        Connection con = null;
        Statement stmt = null;

        try {
            Class.forName("org.mariadb.jdbc.Driver");

            con = DriverManager.getConnection(
                    "jdbc:mariadb://localhost:3306/studydb", 
                    "study", "1111");

            con.setAutoCommit(false);

            stmt = con.createStatement();

            String sql = "insert into p1_memb(name,email,pwd,tel,cdt)"
                    + "values('"+ student.getName()
                    + "','"+ student.getEmail()
                    + "',password('"+student.getPassword()
                    + "'),'"+student.getTel()
                    + "',now())";
            
            

            stmt.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);

            ResultSet autogeneratedkey = stmt.getGeneratedKeys();
            autogeneratedkey.next();

            int studentNO = autogeneratedkey.getInt(1);
            String work = student.isWorking()==true ? "Y" : "N";
            
            String sql2 = "insert into p1_stud(sno,schl,work)"
                    +"values('"+studentNO
                    + "','"+student.getSchool()
                    + "','"+work
                    + "')";

            stmt.executeUpdate(sql2);      

            con.commit();
            return 1;

        }catch(Exception e){
            throw new DaoException(e);         
        }finally {
            try {stmt.close();}catch(Exception e){}
            try {con.close();}catch(Exception e){}
        }

    }

    public List<Student> findAll() {

        ArrayList<Student> list = new ArrayList<>();

        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {

            Class.forName("org.mariadb.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mariadb://localhost:3306/studydb", 
                    "study", "1111");

            con.setAutoCommit(false);

            stmt = con.createStatement();

            String sql = "select"+
                    " m.mno,"+
                    " m.name,"+
                    " m.email,"+
                    " m.pwd,"+
                    " s.schl,"+
                    " s.work,"+
                    " m.tel"+
                    " from p1_stud s"+
                    " inner join p1_memb m on s.sno = m.mno";

            rs = stmt.executeQuery(sql);

            while(rs.next()) {
                
                Student s =  new Student();
                s.setNo(rs.getInt("mno"));
                s.setName(rs.getString("name"));
                s.setEmail(rs.getString("email"));
                s.setPassword(rs.getString("pwd"));
                s.setSchool(rs.getString("schl"));
                
                boolean yn = rs.getString("work").equals("Y") ? true : false;
                s.setWorking(yn);
                        
                s.setTel(rs.getString("tel"));  

                list.add(s);
            }

        }catch(Exception e){
            throw new DaoException(e);
        } finally {
            try { rs.close();} catch(Exception e){}
            try { stmt.close();} catch(Exception e){}
            try { con.close();} catch(Exception e){}
        }

        return list;
    }

    public Student findByEmail(String email) {
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
        Class.forName("org.mariadb.jdbc.Driver");
       
        con = DriverManager.getConnection(
                "jdbc:mariadb://localhost:3306/studydb", 
                "study", "1111");

        stmt = con.createStatement();

        rs = stmt.executeQuery(
                        "select"+
                        " m.mno,"+
                        " m.name,"+
                        " m.email,"+
                        " m.pwd,"+
                        " s.schl,"+
                        " s.work,"+
                        " m.tel"+
                        " from p1_stud s"+
                        " inner join p1_memb m on s.sno = m.mno"+
                        " where m.email='" + email+"'");
        
        while(rs.next()){
            Student s = new Student();
            s.setNo(rs.getInt("mno"));
            s.setName(rs.getString("name"));
            s.setEmail(rs.getString("email"));
            s.setSchool(rs.getString("schl"));
            s.setWorking(rs.getBoolean("work"));

            return s;
         } 
        return null;
        } catch (Exception e){
            throw new DaoException(e);
        } finally {
            try {rs.close();} catch (Exception e) {}
            try {stmt.close();} catch (Exception e) {}
            try {con.close();} catch (Exception e) {}
        }
        

  }
    public Student findByNo(int no) {

        ResultSet rs =null;
        Connection con = null;
        Statement stmt = null;


        try{ 
            Class.forName("org.mariadb.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mariadb://localhost:3306/studydb",
                    "study","1111" );

            con.setAutoCommit(false);

            stmt = con.createStatement();

            String sql = "select"+
                    " m.mno,"+
                    " m.name,"+
                    " m.email,"+
                    " m.pwd,"+
                    " s.schl,"+
                    " s.work,"+
                    " m.tel"+
                    " from p1_stud s"+
                    " inner join p1_memb m on s.sno = m.mno"
                    + "where m.mno=" +no;

            rs = stmt.executeQuery(sql);

            while(rs.next()){
                Student s = new Student();
                s.setNo(rs.getInt("mno"));
                s.setName(rs.getString("name"));
                s.setEmail(rs.getString("email"));
                s.setSchool(rs.getString("schl"));
                s.setWorking(rs.getBoolean("work"));

                return s;

            }
            return null;
        }catch(Exception e) {
            throw new DaoException(e); 
        }finally {
            try{rs.close();}catch(Exception e) {}
            try{stmt.close();}catch(Exception e) {}
            try{con.close();}catch(Exception e) {}
        }
       

    }


    public int deleteByNo(int no) {
        
        
        Connection con = null;
        Statement stmt = null;
       
        
        try {
            
            Class.forName("org.mariadb.jdbc.Driver");
    
            con = DriverManager.getConnection(
                    "jdbc:mariadb://localhost:3306/studydb", 
                    "study", "1111");
      
            con.setAutoCommit(false);
            stmt = con.createStatement();
           
            String sql = ("delete from p1_stud where sno =" +no );
           int count = stmt.executeUpdate(sql);
           
           if(count == 0)
               return 0;
          
            
            String sql2 = ("delete from p1_memb where mno =" +no );
            stmt.executeUpdate(sql2);
            
            con.commit();
            return 1;
 
        } catch (Exception e) {
            throw new DaoException(e);
        } finally {
           
            try {stmt.close();} catch (Exception e) {}
            try {con.close();} catch (Exception e) {}
        }

    }

  }


